language: c

env:
  matrix:
    - python=2.6  CONDA_PY=26  CONDA_NPY=18
    - python=2.7  CONDA_PY=27  CONDA_NPY=18
    - python=3.3  CONDA_PY=33  CONDA_NPY=18
    - python=3.4  CONDA_PY=34  CONDA_NPY=18

  global:
    - secure: "Zr61aIMVBf+mMWVM6L401J0Jrl1qI7nr9YTk4HZygk8VHAAMdVgZxY16t6YxKRIOgwDzh28VC6PPL9uU6eCx0hScMM0QLsh+snLpKcLkz+dY2l5YbiexNTYYTGa9oIeQRQhuxYB2arWDVy+d7wi63V6QnUOlncIJbon0CWaE49Q="

install:
  - source continuous-integration/travis/install.sh

script:
  - conda install --yes setuptools numpy cython
  - python setup.py bdist_conda
  #- conda build conda-recipe --quiet

after_success:
  - python continuous-integration/move-conda-package.py conda-recipe
  - binstar -t $BINSTAR_TOKEN upload --force *.tar.bz2
