package:
  name: pyappveyordemo
  # version: "1.0"
  # the version is actually being set by the __conda_version__.txt file
  # http://conda.pydata.org/docs/build.html#post-build-version

requirements:
  build:
    - python
    - cython
    - numpy
    - setuptools

  run:
    - python
    - numpy

about:
  home: https://github.com/rmcgibbo/python-appveyor-conda-example
  license: MIT
